# Generated by Django 5.2.10 on 2026-01-07 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المادة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_pricing', 'بانتظار التسعير'), ('pending_approval', 'بانتظار الموافقة'), ('approved', 'موافق عليه'), ('partially_approved', 'موافق عليه جزئياً'), ('declined', 'مرفوض'), ('acknowledged', 'تم الإطلاع')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('priced_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسعير')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القرار')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات المدير')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_orders', to=settings.AUTH_USER_MODEL, verbose_name='تم القرار بواسطة')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='departments.department', verbose_name='الشعبة')),
                ('priced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priced_orders', to=settings.AUTH_USER_MODEL, verbose_name='تم التسعير بواسطة')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='اسم المادة')),
                ('item_description', models.TextField(blank=True, verbose_name='وصف المادة')),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='order_items/', verbose_name='صورة المادة')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='السعر (دينار عراقي)')),
                ('item_status', models.CharField(choices=[('pending', 'معلق'), ('approved', 'موافق عليه'), ('declined', 'مرفوض'), ('modified', 'معدل')], default='pending', max_length=20, verbose_name='حالة المادة')),
                ('approved_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='الكمية الموافق عليها')),
                ('admin_note', models.TextField(blank=True, verbose_name='ملاحظة المدير')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.item', verbose_name='المادة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'مادة في الطلب',
                'verbose_name_plural': 'مواد الطلب',
            },
        ),
    ]
