# Generated by Django 5.2.10 on 2026-01-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending_pricing', 'بانتظار الموافقة'), ('pending_approval', 'بانتظار الموافقة'), ('approved', 'موافق عليه'), ('partially_approved', 'موافق عليه جزئياً'), ('declined', 'مرفوض'), ('acknowledged', 'تم الإطلاع')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
    ]
