# Generated by Django 5.2.10 on 2026-01-08 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0002_branch_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='departments.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('department_user', 'مسؤول الشعبة'), ('procurement_committee', 'لجنة المشتريات'), ('administrator', 'المدير'), ('storage_user', 'مخزن')], default='department_user', max_length=30, verbose_name='الدور'),
        ),
    ]
