# Generated by Django 5.2.10 on 2026-01-08 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_branch_alter_department_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المادة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='departments.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_storage_items', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='departments.department', verbose_name='الشعبة')),
            ],
            options={
                'verbose_name': 'مادة في المخزن',
                'verbose_name_plural': 'مواد المخزن',
                'ordering': ['-created_at'],
            },
        ),
    ]
