# Generated by Django 5.2.10 on 2026-01-08 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'إنشاء'), ('updated', 'تعديل'), ('deleted', 'حذف')], max_length=20, verbose_name='الإجراء')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('old_name', models.CharField(blank=True, max_length=200, verbose_name='الاسم السابق')),
                ('new_name', models.CharField(blank=True, max_length=200, verbose_name='الاسم الجديد')),
                ('old_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='الكمية السابقة')),
                ('new_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='الكمية الجديدة')),
                ('old_description', models.TextField(blank=True, verbose_name='الوصف السابق')),
                ('new_description', models.TextField(blank=True, verbose_name='الوصف الجديد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_item_changes', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('storage_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='storage.storageitem', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'سجل تعديل',
                'verbose_name_plural': 'سجل التعديلات',
                'ordering': ['-changed_at'],
            },
        ),
    ]
